# Numpy

In [1]:
import numpy as np

## Creating a 1-dimensional array

In [2]:
one_dimension = [1,2,3]

## Creating a 2-dimensional array

In [4]:
two_dimension = ([1,2,3], [4,5,6])

## Datatypes & Attributes

In [5]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]
              ]])

In [8]:
print(a2)

[[1.  2.  3.3]
 [4.  5.  6.5]]


In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a3.shape

(2, 3, 3)

### to checkout what type of dimension an array has


In [11]:
a1.ndim, a2.ndim , a3.ndim

(1, 2, 3)

### to checkout what datatype the arrays are

In [12]:
a1.dtype, a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

### to checkout the size of the arrays

In [13]:
a1.size ,  a2.size , a3.size

(3, 6, 18)

## Creating a Dataframe from a Numpy array

In [14]:
import pandas as pd


In [15]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [16]:
df3 = pd.DataFrame(a3.reshape(2,9))
df3

0   1   2   3   4   5   6   7   8
0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zero = np.zeros((2,3))

In [22]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,12,2)
range_array

array([ 0,  2,  4,  6,  8, 10])

In [24]:
random_array = np.random.randint(0,10,size = (3,5))
random_array

array([[7, 6, 8, 7, 2],
       [3, 6, 1, 7, 4],
       [7, 0, 7, 5, 2]])

In [25]:
random_array = np.random.random((3,5))
random_array

array([[0.35191214, 0.76509575, 0.12750174, 0.99151524, 0.95155771],
       [0.57319483, 0.81790356, 0.22790856, 0.61535306, 0.73933442],
       [0.83884431, 0.26637248, 0.77449786, 0.06695728, 0.98097735]])

In [30]:
#psuedo-random numbers
# np.random.see()
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[6, 5, 0],
       [6, 3, 1],
       [1, 8, 8],
       [4, 0, 9],
       [7, 0, 1]])

## Viewing arrays and matrices

In [31]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [37]:
a3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a4  = np.random.randint(10, size= (2,3,5,5))
a4

array([[[[8, 1, 5, 9, 8],
         [8, 4, 9, 1, 4],
         [1, 0, 4, 8, 1],
         [0, 2, 2, 3, 9],
         [1, 1, 6, 8, 0]],

        [[1, 7, 1, 6, 3],
         [6, 8, 5, 6, 4],
         [2, 4, 6, 8, 7],
         [3, 9, 2, 2, 9],
         [7, 7, 1, 8, 5]],

        [[5, 4, 0, 8, 7],
         [0, 4, 0, 5, 9],
         [1, 0, 4, 7, 2],
         [1, 0, 6, 7, 8],
         [7, 4, 5, 7, 1]]],


       [[[3, 5, 3, 7, 3],
         [9, 7, 6, 7, 4],
         [8, 9, 4, 8, 0],
         [8, 6, 8, 6, 7],
         [7, 2, 6, 4, 7]],

        [[6, 3, 3, 4, 1],
         [3, 6, 6, 0, 5],
         [5, 7, 8, 2, 9],
         [0, 3, 4, 9, 1],
         [9, 4, 3, 6, 0]],

        [[5, 2, 1, 2, 5],
         [6, 1, 3, 9, 0],
         [2, 5, 7, 3, 4],
         [8, 7, 1, 5, 4],
         [3, 5, 0, 8, 7]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 5, 5), 4)

In [41]:
## getting the first 4 numbers of the innermost arrays
a4[:,:,:,:1]

array([[[[8],
         [8],
         [1],
         [0],
         [1]],

        [[1],
         [6],
         [2],
         [3],
         [7]],

        [[5],
         [0],
         [1],
         [1],
         [7]]],


       [[[3],
         [9],
         [8],
         [8],
         [7]],

        [[6],
         [3],
         [5],
         [0],
         [9]],

        [[5],
         [6],
         [2],
         [8],
         [3]]]])

## Manipulating & comparing arrays

In [42]:
a1

array([1, 2, 3])

In [44]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones  #same applies for subtraction, multiplication, division& the rest. 

array([2., 3., 4.])

In [46]:
a1

array([1, 2, 3])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [49]:
np.log(a1)  #for logrithm

array([0.        , 0.69314718, 1.09861229])